PUT http://localhost:4000/api/returnProduct/3
Content-Type: application/json

{    
    "COD_PRODUCT": 5,
    "CONCEPT": "QUEBRADITO",
    "CANT_PRODUCT" : 1,
    "NUM_LOT": 1,
    "COD_USER": null,
    "MOVEMENT": "SALIDA",
    "DES_RETURN": "QUEBRADITO"
}