GET http://localhost:4000/api/inventoryTransactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDT0RfVVNFUiI6MSwiQ09EX1JPTEUiOjEsIkZJUlNUX05BTUUiOiJEYXZpZCIsIkxBU1RfTkFNRSI6IlJpdmFzIiwiaWF0IjoxNjUwNTA2Nzk4LCJleHAiOjE2NTA1NjA3OTh9.hIgtDLsdT793Axp6zkxyYr0p1C5v-rXo8Za2R_mkVTU
