PUT http://localhost:4000/api/pay-form/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDT0RfUk9MRSI6MSwiRklSU1RfTkFNRSI6Ik1lbmRlbCIsIkxBU1RfTkFNRSI6IlJvbWVybyIsImlhdCI6MTY0OTIyMzc0OX0.4_lFWGfTx4pdRV3fN6trLo6xTvtDlONIjQ00HoATxS8

{
	"HOURS_WORKED": 20,
    "AMO_GROSS": 20000.00,
    "BONUS": 1500.00,
    "TOT_DEDUCTIONS": 250.00,
    "NET_SALARY": 19800.00,
    "DAT_PAYMENT": "2021-05-02",
    "COD_USER": 4
}