POST http://localhost:4000/api/notifications
Content-Type: application/json

{
    "COD_ROLE": 2, 
    "MESSAGE": "Tienes nuevos productos por revisar.", 
    "TYP_NOTIFICATION": "Control de calidad"
}