POST http://localhost:4000/api/supplier
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDT0RfUk9MRSI6MSwiRklSU1RfTkFNRSI6IlBlZHJvIiwiTEFTVF9OQU1FIjoiU2FuY2hleiIsImlhdCI6MTY0NzM5MDI1M30.cn1xro2BAtDzbgoNloL6o2j9sQpY4UI41kOH3mZ-_Q8


{
	"NAM_SUPPLIER": "Pepsi",
	"NAM_CONTACT": "Romeo",
	"LAST_NAM_CONTACT": "Santos",
	"ADDRESS": "jutiapa danli",
	"NUM_PHONE_ONE": 98745623,
	"EMAIL":"pepsi@gmail.com",
	"NAM_CITY": "Tegucigalpa",
	"ZIP_CODE": 504
}