POST http://localhost:4000/api/sale-invoice
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDT0RfUk9MRSI6MSwiRklSU1RfTkFNRSI6IlJvZHJpZ28iLCJMQVNUX05BTUUiOiJWYWxsZSIsImlhdCI6MTY0OTEzMzI1NH0.mr4fe_jAszIn54mBKnfaukZ-sEo7IyJW2CrrDWuQr9M


{
    "COD_CLIENT": 1,
    "COD_USER": 1, 
    "SUBTOTAL": 100,
    "TOT_DISCOUNT": 0,
    "TOT_ISV": 25,
    "TOT_SALE": 290,
    "TYP_TO_SALE": "Contado",
    "COD_TYP_PAY": 1 
}