POST http://localhost:4000/api/sale-invoice
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDT0RfUk9MRSI6MSwiRklSU1RfTkFNRSI6IlBlZHJvIiwiTEFTVF9OQU1FIjoiU2FuY2hleiIsImlhdCI6MTY0NzM5MDI1M30.cn1xro2BAtDzbgoNloL6o2j9sQpY4UI41kOH3mZ-_Q8

{
    "COD_CLIENT": 1,
    "COD_USER": 1, 
    "SUBTOTAL": 1500,
    "TOT_DISCOUNT": 0,
    "TOT_ISV": 25,
    "TOT_SALE": 290,
    "TYP_TO_SALE": "Contado",
    "COD_TYP_PAY": 1 
}