PUT http://localhost:4001/api/purchase-invoice/2
Content-Type: application/json

{
    "SUBTOTAL": 100,
    "TOT_DISCOUNT": 500 ,
    "TOT_ISV": 3000,
    "TOT_PURCHASE": 100,
    "TYP_TO_PURCHASE": "Contado",
    "COD_TYP_PAY": 1,
    "DAT_INVOICE": "2022-12-10",
    "COD_ORDER": "2",
    "COD_USER": "1"
}