GET http://localhost:4000/api/inventoryCategory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDT0RfVVNFUiI6MSwiQ09EX1JPTEUiOjEsIkZJUlNUX05BTUUiOiJEYXZpZCIsIkxBU1RfTkFNRSI6IlJpdmFzIiwiaWF0IjoxNjUwNjYwOTI3LCJleHAiOjE2NTA3MTQ5Mjd9.xNiXMrntm-B10ZEBl8qhXL6hQZO1ES9t0m8qSvOFLVk