POST http://localhost:4000/api/inventory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDT0RfVVNFUiI6MSwiQ09EX1JPTEUiOjEsIkZJUlNUX05BTUUiOiJSb2RyaWdvIiwiTEFTVF9OQU1FIjoiVmFsbGUiLCJpYXQiOjE2NTAzNTMyNjEsImV4cCI6MTY1MDQwNzI2MX0.lOnacoUnUn8nBxuDW19DkN93UFhIKgZhxiSscnnaCL0

{
    "COD_SUPPLIER" : 1,
	"NAM_PRODUCT" : "Requeson",
    "DES_PRODUCT" : "Salado",
    "ISV" : 0.15,
    "NORMAL_UNIT_PRICE": 100.00,
    "WHOLESALE_CANT" : 105.00,
    "WHOLESALE_PRICE" : 105.00,
    "PURCHASE_PRICE": 90.00,
    "COD_CATEGORY": 2,
    "COD_TYP_PRODUCT": 1
}