POST http://localhost:4000/api/inventory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDT0RfUk9MRSI6MSwiRklSU1RfTkFNRSI6IlBlZHJvIiwiTEFTVF9OQU1FIjoiU2FuY2hleiIsImlhdCI6MTY0NzM5MDI1M30.cn1xro2BAtDzbgoNloL6o2j9sQpY4UI41kOH3mZ-_Q8

{
    "COD_SUPPLIER" : 1,
	"NAM_PRODUCT" : "Medallones",
    "DES_PRODUCT" : "Caja de medallos",
    "ISV" : 0.15,
    "NORMAL_UNIT_PRICE": 100.00,
    "WHOLESALE_CANT" : 105.00,
    "WHOLESALE_PRICE" : 105.00,
    "PURCHASE_PRICE": 90.00,
    "COD_CATEGORY": 1,
    "COD_TYP_PRODUCT": 1
}