POST http://Localhost:4000/api/client
Content-Type: application/json

{
    "IDENTITY":"080119992072",
    "FIRST_NAME":"Carlos",
    "LAST_NAME":"Roguez",
    "ADDRESS":"Villanueva",
    "NUM_PHONE_ONE":89754123,
    "RTN": "08180361089"
}