GET http://localhost:4000/api/accounts-receivable
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDT0RfUk9MRSI6MSwiRklSU1RfTkFNRSI6IlBlZHJvIiwiTEFTVF9OQU1FIjoiU2FuY2hleiIsImlhdCI6MTY0NzA1NDczOH0.P_mJn313Zuant1XDIhm6Y4Wfk2Pyko4797Z0HeBQVLM