POST http://localhost:4000/api/user
Content-Type: application/json 

{
    "IDENTITY": "0801199912345",
    "FIRST_NAME": "Luis",
    "MIDDLE_NAME": "Eduardo",
    "LAST_NAME": "Garcia",
    "SECOND_LAST_NAME": "Mendez",
    "GENDER": "M",
    "NUM_PHONE_ONE": 88795986,
    "NUM_REFERENCE": 22101972,
    "DAT_BIRTHDAY": "1998-02-12",
    "NAM_CITY": "Tegucigalpa",
    "ADDRESS": "Res. Plaza",
    "COD_STATUS": 1,
    "COD_ROLE": 1,
    "USER_EMAIL": "luis@hotmail.com",
    "USER_PASSWORD": "Hook23"
}