PUT http://localhost:4000/api/user/4
Content-Type: application/json

{
    "IDENTITY": "080119990531",
    "FIRST_NAME": "Mendel",
    "MIDDLE_NAME": "Brazchid",
    "LAST_NAME": "Aguilar",
    "GENDER": "M",
    "NUM_PHONE_ONE": 88795976,
    "NUM_PHONE_REFERENCE": 78451236,
    "DAT_BIRTHDAY": "1998-02-12",
    "NAM_CITY": "Tegucigalpa",
    "ADDRESS": "Res. Plaza",
    "COD_ROLE": 1,
    "USER_EMAIL": "mendelaguilar@hotmail.com",
    "USER_PASSWORD": "1234"
}