GET http://localhost:4000/api/order-detail/3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDT0RfVVNFUiI6MSwiQ09EX1JPTEUiOjEsIkZJUlNUX05BTUUiOiJSb2RyaWdvIiwiTEFTVF9OQU1FIjoiVmFsbGUiLCJpYXQiOjE2NTA5ODYwNTMsImV4cCI6MTY1MTA0MDA1M30.7khUPnhtM4lm_A8Iggt9kman3MKK3dMgOmxwkRrPGlg
